app/__init__.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from flask import Flask, render_template
from flask_moment import Moment

from config import config

# Initialize plugins.
moment = Moment()

# App factory function.
def create_app(config_name):
    ''' Create an app from a specific configure.
    '''
    app = Flask(__name__)
    app.config.from_object(config[config_name])
    config[config_name].init_app(app)

    # Register blueprint.
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    moment.init_app(app)

    return app

app/main/__init__.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

''' Blueprint
'''

import time

from flask import Blueprint

main = Blueprint('main', __name__)

__version__ = '0.1.0'

FILE_HEADER = (
    '# This file was automatically generated by KinLab' +
    ' (https://github.com/PytLab/KinLab).\n' +
    '# Version %s\n# Date: %s \n#\n' +
    '# Do not make changes to this file ' +
    'unless you know what you are doing\n\n') % (__version__, time.asctime())

from .files import *
from .model import *
from .job import *
from .report import *

app/main/views.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

# View functions for microkinetics model building.

import os
from collections import namedtuple
from datetime import datetime

from flask import request
from flask import render_template, url_for
from flask import make_response, send_file, redirect, abort

from . import main
from .errors import PathError
from .utils import file_mtime, file_ctime, file_size

# Global variables.
CODE_SUFFIXES = dict(py='python',
                     c='c',
                     cpp='c',
                     html='html',
                     css='css',
                     js='javascript',
                     h='c',
                     conf='text',
                     txt='text')

TEXT_SUFFIXES = dict(conf='text',
                     txt='text',
                     md='text',
                     log='text')

ZIP_SUFFIXES = ['zip', 'rar', 'tar', 'tgz', '7z', 'gz']

FILE_SUFFIXES = {**CODE_SUFFIXES, **TEXT_SUFFIXES}

@main.route('/')
def index():
    return redirect(url_for('main.filetree'))

@main.route('/files/', defaults={'path': ''})
@main.route('/files/<path:path>')
def filetree(path):
    # Parameters passed to template.
    locs = {}

    # Activate navigation tab.
    locs['files'] = 'active'

    # Current path information.
    base_path = os.getcwd()
    full_path = '{}/{}'.format(base_path, path)

    # Path information.
    if path:
        if not os.path.exists(full_path):
            raise PathError('No such file or directory: {}'.format(full_path))
        path = [subdir for subdir in path.split('/') if subdir]

        # Directory backward.
        prev_path = '/'.join(path[: -1])

        # Links for each subdir in path information.
        path_links = []
        base_link = url_for('main.filetree')[:-1]
        accumulate_link = base_link
        for subdir in path:
            accumulate_link += ('/' + subdir)
            path_links.append(accumulate_link)
        links_paths = zip(path_links, path)
    else:
        links_paths = []

    locs['links_paths'] = links_paths

    # Show file tree.
    if os.path.isdir(full_path):
        # File list.
        dirs_files  = os.listdir(full_path)
        dirs = [i for i in dirs_files if os.path.isdir('{}/{}'.format(full_path, i))]
        files = [i for i in dirs_files if os.path.isfile('{}/{}'.format(full_path, i))]

        url = request.url.strip('/')

        # Store information for each item in file table.
        FileItem = namedtuple('FileItem', ['name', 'link', 'mtime'])

        dir_items = []
        for dir in sorted(dirs):
            link = '{}/{}'.format(url, dir)
            mtime = file_mtime('{}/{}'.format(full_path, dir))
            dir_item = FileItem._make([dir, link, mtime])
            dir_items.append(dir_item)

        file_items = []
        for file in sorted(files):
            link = '{}/{}'.format(url, file)
            mtime = file_mtime('{}/{}'.format(full_path, file))
            file_item = FileItem._make([file, link, mtime])
            file_items.append(file_item)

        locs['file_items'], locs['dir_items'] = file_items, dir_items

        # File types.
        locs['code_suffixes'] = CODE_SUFFIXES
        locs['text_suffixes'] = TEXT_SUFFIXES
        locs['zip_suffixes'] = ZIP_SUFFIXES

        # Previous link.
        if path:
            locs['prev_link'] = '/'.join(url.split('/')[: -1])
        else:
            locs['prev_link'] = None

        return render_template('files/file_tree.html', **locs)
    else:
        file_suffix = full_path.split('.')[-1]

        # Show text file content.
        if file_suffix in FILE_SUFFIXES:
            with open(full_path, 'r') as f:
                file_content = f.read()
            locs['file_content'] = file_content
            locs['file_type'] = FILE_SUFFIXES[file_suffix]
            locs['mtime'] = file_mtime(full_path)
            locs['filesize'] = file_size(full_path)
            locs['filename'] = full_path.split('/')[-1]
            return render_template('files/file_content.html', **locs)
        # Download the file.
        else:
            response = make_response(send_file(full_path))
            filename = full_path.split('/')[-1]
            response.headers["Content-Disposition"] = "attachment; filename={};".format(filename)
            return response

@main.route('/model/')
def model():
    locs = {}

    # Activate navigation tab.
    locs['model'] = 'active'
    return render_template('model/model.html', **locs)

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	{% block title %}{% endblock %}
    <link href="{{ url_for('static', filename='css/externals/bootstrap/bootstrap.min.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='css/externals/font-awesome/css/font-awesome.min.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='css/externals/rainbow/monokai.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='css/externals/rainbow/rainbow-linenumbers.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='css/scaks.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='img/icon.ico') }}" rel="icon">
</head>
<body>
	{% block navbar %}
    {% include "nav/navbar.html" %}
    {% endblock %}

    <div class="container">
        <div class="col-md-1"></div>
        <div class="col-md-10">
        {% block content %}
        {% endblock %}
        </div>
        <div class="col-md-1"></div>
    </div>

    {% block script %}
    <script src="{{ url_for('static', filename='js/externals/jquery/jquery-3.2.1.js') }}"></script>
    <script src="{{ url_for('static', filename='js/externals/bootstrap/bootstrap.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/externals/moment/moment-with-locales.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/externals/rainbow/rainbow.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/externals/rainbow/rainbow.linenumbers.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/scaks/scaks.js') }}"></script>
    <script src="{{ url_for('static', filename='js/scaks/rxn_panel.js') }}"></script>
    <script src="{{ url_for('static', filename='js/scaks/rxn_definition.js') }}"></script>
    <script src="{{ url_for('static', filename='js/scaks/energy_profile.js') }}"></script>
    <script src="{{ url_for('static', filename='js/form_status/form_status.js') }}"></script>
    <script src="{{ url_for('static', filename='js/rxn-parser/rxn_parser.js') }}"></script>
    <script src="{{ url_for('static', filename='js/scaks/model_panel.js') }}"></script>
    <script src="{{ url_for('static', filename='js/externals/highcharts/highcharts.js') }}"></script>
    {{ moment.include_moment() }}
    {% endblock %}
</body>
</html>

app/templates/file_content.html
{% extends "base.html" %}

{% block content %}
{% include "navtabs.html" %}
{% include "file_path.html" %}

<!-- File info -->
<div class="row">
    <div class="well well-sm embeded-charactors">
        <div class="row file-info">
            <div class="col-xs-12 col-sm-4 text-center">
                <i class="fa fa-file"></i>{{ filename }}
            </div>
            <div class="col-xs-12 col-sm-4 text-center">
                <i class="fa fa-clock-o"></i>{{ moment(mtime).format('LLL') }}
            </div>
            <div class="col-xs-12 col-sm-4 text-center">
                <i class="fa fa-file-archive-o"></i>{{ filesize }}
            </div>
        </div>
    </div>
</div>

<!-- File content -->
<div class="row">
    <pre><code data-language="{{ file_type }}">{{ file_content }}</code></pre>
</div>
{% endblock %}

app/templates/filepath.html
<!-- Bread crumb navigator for file location -->
<div class="row">
    <ul class="breadcrumb with-margin-top">
        <li><a href="{{ url_for('main.index') }}"><i class="fa fa-home" aria-hidden="true"></i></a></li>
        {% for link, subdir in links_paths %}
        <li><b><a href="{{ link }}">{{ subdir }}</a></b></li>
        {% endfor %}
    </ul>
</div>

app/templates/files/file_buttons.html
<div class="row">
    <div class="row file-buttons">
        <div class="col-xs-12 col-sm-6 col-md-6 with-margin-bottom">
            <a class="btn btn-sm btn-success" href="{{ url_for('main.model', path=path) }}" target="_blank"><i class="fa fa-plus"></i><b>Create or open a job</b></a>
        </div>

        <div class="col-xs-12 col-sm-6 col-md-6 text-right with-margin-bottom">
            <div class="btn-group btn-group-sm with-margin-bottom">
                <button type="button" class="btn btn-default disabled"><i class="fa fa-upload"></i><b>Upload</b></button>
                <button type="button" class="btn btn-default disabled"><i class="fa fa-download"></i><b>Download</b></button>
                <button type="button" class="btn btn-default" id="refresh-file-table">
                    <i class="fa fa-refresh"></i><b>Refresh</b>
                </button>
                <button type="button" class="btn btn-danger disabled"><i class="fa fa-trash"></i><b>Delete</b></button>
            </div>
        </div>
    </div>
</div>

app/templates/files/file_content.html
{% extends "base.html" %}

{% block content %}
{% include "nav/navtabs.html" %}
{% include "files/file_path.html" %}

<!-- File info -->
<div class="row">
    <div class="well well-sm embeded-charactors">
        <div class="row file-info">
            <div class="col-xs-12 col-sm-4 text-center">
                <i class="fa fa-file"></i>{{ filename }}
            </div>
            <div class="col-xs-12 col-sm-4 text-center">
                <i class="fa fa-clock-o"></i>{{ moment(mtime).format('LLL') }}
            </div>
            <div class="col-xs-12 col-sm-4 text-center">
                <i class="fa fa-file-archive-o"></i>{{ filesize }}
            </div>
        </div>
    </div>
</div>

<!-- File content -->
<div class="row">
    {% if file_content %}
    <pre class="file-content"><code data-language="{{ file_type }}">{{ file_content }}</code></pre>
    {% else %}
    <div class="well well-lg">
        <div class="embeded-charactors"><h5>The file is empty (。_。)...</h5></div>
    </div>
    {% endif %}
</div>
{% endblock %}

app/templates/files/file_path.html
<!-- Bread crumb navigator for file location -->
<div class="row">
    <ul class="breadcrumb with-margin-top">
        <li><a href="{{ url_for('main.index') }}"><i class="fa fa-home" aria-hidden="true"></i></a></li>
        {% for link, subdir in links_paths %}
        <li><b><a href="{{ link }}">{{ subdir }}</a></b></li>
        {% endfor %}
    </ul>
</div>

app/templates/files/file_table.html
<!-- File table -->
<div class="row">
    <div class="table-responsive" id="file-table">
        <table class="table table-hover">
            <tbody>
                {% if prev_link %}
                <tr><td><i class="fa fa-folder-o"></i><a href="{{ prev_link }}"><span>..</span></a></td></tr>
                {% endif %}
            {% if dir_items %}
                {% for dir_item in dir_items %}
                <tr>
                    <td>
                        <i class="fa fa-folder-o"></i><a href="{{ dir_item.link }}"><b>{{ dir_item.name }}</b></a>
                        <span class="embeded-charactors pull-right">
                        {{ moment(dir_item.mtime).fromNow(refresh=True) }}
                        </span>
                    </td>
                </tr>
                {% endfor %}
            {% endif %}
            {% if file_items %}
                {% for file_item in file_items %}
                    {% if file_item.name.split('.')[-1] in code_suffixes %}
                <tr>
                    <td>
                        <i class="fa fa-file-code-o"></i><a href="{{ file_item.link }}">{{ file_item.name }}</a>
                        <span class="embeded-charactors pull-right">
                        {{ moment(file_item.mtime).fromNow(refresh=True) }}
                        </span>
                    </td>
                </tr>
                {% elif file_item.name.split('.')[-1] in text_suffixes %}
                <tr>
                    <td>
                        <i class="fa fa-file-text-o"></i><a href="{{ file_item.link }}">{{ file_item.name }}</a>
                        <span class="embeded-charactors pull-right">
                        {{ moment(file_item.mtime).fromNow(refresh=True) }}
                        </span>
                    </td>
                </tr>
                {% elif file_item.name.split('.')[-1] in zip_suffixes %}
                <tr>
                    <td>
                        <i class="fa fa-file-zip-o"></i><a href="{{ file_item.link }}">{{ file_item.name }}</a>
                        <span class="embeded-charactors pull-right">
                        {{ moment(file_item.mtime).fromNow(refresh=True) }}
                        </span>
                    </td>
                </tr>
                {% else %}
                <tr>
                    <td>
                        <i class="fa fa-file-o"></i><a href="{{ file_item.link }}">{{ file_item.name }}</a>
                        <span class="embeded-charactors pull-right">
                        {{ moment(file_item.mtime).fromNow(refresh=True) }}
                        </span>
                    </td>
                </tr>
                    {% endif %}
                {% endfor %}
            {% endif %}
            </tbody>
        </table>
    </div>
</div>

app/templates/files/file_tree.html
{% extends "base.html" %}

{% block content %}
{% include "nav/navtabs.html" %}
{% include "files/file_path.html" %}
{% include "files/file_buttons.html" %}
{% include "files/file_table.html" %}
{% endblock %}

app/templates/filesystem.html
{% extends "base.html" %}

{% block navbar %}
{% include "navbar.html" %}
{% endblock %}

{% block content %}
<div class="container">
{% include "navtabs.html"%}
{% include "filepath.html" %}
</div>
{% endblock %}

app/templates/filetable.html
<!-- File table -->
<div class="row">
    <div class="table-responsive">
        <table class="table table-hover filetree">
            <tbody>
                {% if prev_link %}
                    <tr><td><i class="fa fa-folder-o"></i><a href="{{ prev_link }}">..</a></td></tr>
                {% endif %}
            {% if dir_items %}
                {% for dir_item in dir_items %}
                <tr>
                    <td>
                        <i class="fa fa-folder-o"></i><a href="{{ dir_item.link }}">{{ dir_item.name }}</a>
                        <span class="embeded-charactors pull-right">
                        {{ moment(dir_item.mtime).fromNow(refresh=True) }}
                        </span>
                    </td>
                </tr>
                {% endfor %}
            {% endif %}
            {% if file_items %}
                {% for file_item in file_items %}
                    {% if file_item.name.split('.')[-1] in code_suffixes %}
                <tr>
                    <td>
                        <i class="fa fa-file-code-o"></i><a href="{{ file_item.link }}">{{ file_item.name }}</a>
                        <span class="embeded-charactors pull-right">
                        {{ moment(file_item.mtime).fromNow(refresh=True) }}
                        </span>
                    </td>
                </tr>
                {% elif file_item.name.split('.')[-1] in text_suffixes %}
                <tr>
                    <td>
                        <i class="fa fa-file-text-o"></i><a href="{{ file_item.link }}">{{ file_item.name }}</a>
                        <span class="embeded-charactors pull-right">
                        {{ moment(file_item.mtime).fromNow(refresh=True) }}
                        </span>
                    </td>
                </tr>
                {% elif file_item.name.split('.')[-1] in zip_suffixes %}
                <tr>
                    <td>
                        <i class="fa fa-file-zip-o"></i><a href="{{ file_item.link }}">{{ file_item.name }}</a>
                        <span class="embeded-charactors pull-right">
                        {{ moment(file_item.mtime).fromNow(refresh=True) }}
                        </span>
                    </td>
                </tr>
                {% else %}
                <tr>
                    <td>
                        <i class="fa fa-file-o"></i><a href="{{ file_item.link }}">{{ file_item.name }}</a>
                        <span class="embeded-charactors pull-right">
                        {{ moment(file_item.mtime).fromNow(refresh=True) }}
                        </span>
                    </td>
                </tr>
                    {% endif %}
                {% endfor %}
            {% endif %}
            </tbody>
        </table>
    </div>
</div>

app/templates/filetree.html
{% extends "base.html" %}

{% block content %}
{% include "navtabs.html" %}
{% include "filepath.html" %}
{% include "filetable.html" %}
{% endblock %}

app/templates/job/running.html
{% extends "base.html" %}

{% block content %}
{% include "nav/navtabs.html" %}
{% include "files/file_path.html" %}
{% include "job/running_panel.html" %}
{% endblock %}

{% block script %}
{{ super() }}
<script src="{{ url_for('static', filename='js/scaks/job_running.js') }}"></script>
{% endblock %}

app/templates/job/running_buttons.html
<div id="running-buttons" class="row with-margin-bottom" style="display:none">
    <div class="col-xs-12 col-sm-6 col-md-6">
    <!--
    <button type="button" class="btn btn-sm btn-primary">
        <i class="fa fa-refresh with-margin-right"></i><b>Run again</b>
    </button>
    -->
    </div>

    <div class="col-xs-12 col-sm-6 col-md-6 text-right">
    </div>
</div>

app/templates/job/running_panel.html
<div class="row">
    <!-- store path info -->
    <div id="full-path" data-full-path="{{ full_path }}"></div>
    <div id="running-status" class="alert alert-warning">
        <div class="row" id="job-logo">
            <div class="col-md-6">
                <span id="running">
                <img class="with-margin-right" src="/static/img/snake-20x20.gif" alt="Job is running...">
                Running...
                </span>
                <span id="run-success" style="display: none">
                <i class="fa fa-check with-margin-right"></i>
                Succeed
                </span>
                <span id="run-failure" style="display: none">
                <i class="fa fa-times with-margin-right"></i>
                Failed
                </span>
            </div>
            <div class="col-md-6 text-right">
                <i class="fa fa-clock-o"></i>
                <span id="run-time" class="with-margin-right" style="display: none">
                </span>
                <a id="report-button" class="btn btn-success btn-sm" href="{{ url_for('main.report', path=path) }}" target="blank" style="display: none">
                    <i class="fa fa-list"></i><b>Generate report</b>
                </a>
            </div>
        </div>
    </div>
    {% include "job/running_buttons.html" %}
    <div id="running-log">
        <div class="text-center">
            <img src="/static/img/broken-circle.gif" alt="Loading log...">
        </div>
    </div>
</div>

app/templates/model/energy_profile.html
<!-- Energy profile plotting -->
<div class="modal fade" id="energy-profile">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header embeded-charactors"><i class="fa fa-area-chart"></i>Energy Profile
                <button class="close close-energy-profile" type="button">&times;</button>
            </div>
            <div class="modal-body">
            <div id="energy-profile-container" style="min-width: 300px; min-height: 400px"></div>
            </div>
        </div>
    </div>
</div>

app/templates/model/model.html
{% extends "base.html" %}

{% block content %}
{% include "nav/navtabs.html" %}
{% include "files/file_path.html" %}
{% include "model/panels.html" %}
{% endblock %}

{% block script %}
{{ super() }}
<script>
    window.onbeforeunload = function (event) {
        return confirm();
    }
</script>
{% endblock %}

app/templates/model/model_buttons.html
<!-- Reactions buttons -->
<div id="model-btns" class="row">
    <div class="col-xs-8 col-sm-6 col-md-6 with-margin-bottom">
        <a id="run-model" class="btn btn-sm btn-success" href="{{ url_for('main.running', path=path) }}" target="_blank"><i class="fa fa-play"></i><b>Run</b></a>
        <button type="button" id="save-model" class="btn btn-sm btn-primary"><i class="fa fa-floppy-o"></i><b>Save</b></button>
        <button type="button" id="reset-model" class="btn btn-sm btn-default"><i class="fa fa-refresh"></i><b>Reset</b></button>
        <img class="with-margin-left" src="/static/img/broken-circle-20x20.gif" alt="Loading" style="display: none">
    </div>
    <div class="col-xs-4 col-sm-6 col-md-6 text-right with-margin-bottom">
        <button type="button" id="load-species-form" class="btn btn-sm btn-warning"><i class="fa fa-refresh"></i><b>Load</b></button>
    </div>
</div>

app/templates/model/model_form.html
<div id="model-form" class="row with-margin-top">
    <div class="col-md-6">
        <div class="row">
            <div class="col-md-12">
                <div id="model-param-form">
                    <div class="input-group with-margin-bottom">
                        <span class="input-group-addon" data-toggle="tooltip" data-original-title="Reaction temperature">T</span>
                        {% if model_info and model_info.get('temperature') %}
                        <input type="text" name="temperature" value="{{model_info['temperature']}}" class="form-control" placeholder="Temperature">
                        {% else %}
                        <input type="text" name="temperature" class="form-control" placeholder="Temperature">
                        {% endif %}
                        <span class="input-group-addon" data-toggle="tooltip" data-original-title="Kelvin">K</span>
                    </div>
                    <div class="input-group with-margin-bottom">
                        <span class="input-group-addon" data-toggle="tooltip" data-original-title="Max iteration steps">Max Iteration</span>
                        {% if model_info and model_info.get('max_iteration') %}
                        <input type="text" name="max-iteration" value="{{ model_info.get('max_iteration') }}" class="form-control" placeholder="Max iteration step">
                        {% else %}
                        <input type="text" name="max-iteration" class="form-control" placeholder="Max iteration step" value="100">
                        {% endif %}
                    </div>
                    <div class="input-group with-margin-bottom">
                        <span class="input-group-addon" data-toggle="tooltip" data-original-title="Error convergence criterion">Tolerance</span>
                        {% if model_info and model_info.get('tolerance') %}
                        <input type="text" name="tolerance" class="form-control" placeholder="Convergence Criterion" value="{{ model_info.get('tolerance') }}">
                        {% else %}
                        <input type="text" name="tolerance" class="form-control" placeholder="Convergence Criterion" value="1e-50">
                        {% endif %}
                    </div>
                    <div class="input-group with-margin-bottom">
                        <span class="input-group-addon" data-toggle="tooltip" data-original-title="Algorithm for rate calculation">Rate Theory</span>
                        <select name="rate-algo" class="form-control">
                        {% if model_info and model_info.get('rate_algo') %}
                            {% if model_info.get('rate_algo') == 'CT' %}
                            <option value="TST">Transtion State Theory</option>
                            <option value="CT" selected>Collision Theory</option>
                            {% else %}
                            <option value="TST" selected>Transtion State Theory</option>
                            <option value="CT">Collision Theory</option>
                            {% endif %}
                        {% else %}
                            <option value="TST" selected>Transtion State Theory</option>
                            <option value="CT">Collision Theory</option>
                        {% endif %}
                        </select>
                    </div>
                    {% if model_info.get('rate_algo') == 'CT' %}
                    <div class="input-group with-margin-bottom">
                        <span class="input-group-addon" data-toggle="tooltip" data-original-title="Unitcell area">Unit Area</span>
                        <input type="text" name="unitcell-area" class="form-control" placeholder="Unitcell area" value="{{ model_info.get('unitcell_area') }}">
                        <span class="input-group-addon" data-toggle="tooltip" data-original-title="Square meter">m<sup>2</sup></span>
                    </div>
                    <div class="input-group with-margin-bottom">
                        <span class="input-group-addon" data-toggle="tooltip" data-original-title="Ratio of active area in unitcell">Active Ratio</span>
                        <input type="text" name="active-ratio" class="form-control" placeholder="active area / unit cell area" value="{{ model_info.get('active_ratio') }}">
                    </div>
                    {% endif %}
                    <div class="input-group with-margin-bottom">
                        <span class="input-group-addon" data-toggle="tooltip" data-original-title="Rootfinding iterator">RootFinding</span>
                        <select name="root-finding" class="form-control">
                        {% if model_info and model_info.get('rootfinding') %}
                            {% if model_info.get('rootfinding') == 'ConstrainedNewton' %}
                            <option value="MDNewton">MD Newton</option>
                            <option value="ConstrainedNewton" selected>Constrained Newton</option>
                            {% else %}
                            <option value="MDNewton" selected>MD Newton</option>
                            <option value="ConstrainedNewton">Constrained Newton</option>
                            {% endif %}
                        {% else %}
                            <option value="MDNewton" selected>MD Newton</option>
                            <option value="ConstrainedNewton">Constrained Newton</option>
                        {% endif %}
                        </select>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div id="species-properties" class="col-md-6">
        <div class="row">
            <div class="col-md-12">
                {% if model_info and (model_info.get('gas_pressures') or model_info.get('site_total_cvgs')) %}
                <div id="species-form">
                    {% for gas, pressure in model_info.get('gas_pressures') %}
                    <div class="pressure-input input-group with-margin-bottom">
                        <span class="input-group-addon" data-toggle="tooltip" data-original-title="{{ gas }} pressure">P<sub>({{ gas }})</sub></span>
                        <input type="text" name="{{ gas }}" class="form-control" placeholder="{{ gas }} pressure" value="{{ pressure }}">
                        <span class="input-group-addon" data-toggle="tooltip" data-original-title="Atmospheric pressure">bar</span>
                    </div>
                    {% endfor %}
                    {% for site, cvg in model_info.get('site_total_cvgs') %}
                    <div class="site-cvg-input input-group with-margin-bottom">
                        <span class="input-group-addon" data-toggle="tooltip" data-original-title="Total coverage of {{ site }}">Total &theta;<sub>({{ site }})</sub></span>
                        <input type="text" name="{{ site }}" class="form-control" placeholder="total coverage" value="{{ cvg }}">
                    </div>
                    {% endfor %}
                </div>
                {% else %}
                <div id="no-species-form" class="well text-center embeded-charactors">
                    No species information, press <b><i class="fa fa-refresh"></i>Load</b> button to load them
                </div>
                <div id="species-form" style="display: none">
                </div>
                {% endif %}
            </div>
        </div>
    </div>
</div>

app/templates/nav/navbar.html
<!-- Navigator bar -->
<nav class="navbar navbar-default">
    <div class="container">
        <div class="row">
            <div class="col-md-1"></div>
            <div class="col-md-10">
                <div class="navbar-header">
                    <a class="navbar-brand" href="/"><strong>SCAKS-Hub</strong></a>
                </div>
            </div>
            <div class="col-md-1"></div>
        </div>
    </div>
</nav>

app/templates/nav/navtabs.html
<!-- Navigator tabs -->
<div class="row">
    <ul class="nav nav-tabs">
        <li class="{{ files }}"><a href="{{ url_for('main.filetree') }}">Files</a></li>
        <li class="{{ model }}"><a href="{{ url_for('main.model') }}">Model</a></li>
        <li class="{{ running }}"><a href="#">Running</a></li>
        <li class="{{ report }}"><a href="#">Report</a></li>
    </ul>
</div>

app/templates/report/no_report.html
{% extends "base.html" %}

{% block content %}
{% include "nav/navtabs.html" %}
{% include "files/file_path.html" %}
<div class="row">
    <div class="panel panel-default">
        <div class="panel-heading embeded-charactors"><i class="fa fa-list"></i>Report</div>
        <div class="panel-body">
        <div class="col-md-12 well embeded-charactors text-center">
            <b>Can't generate report in current directory</b>
        </div>
    </div>
</div>
{% endblock %}

app/templates/report/report.html
{% extends "base.html" %}

{% block content %}
{% include "nav/navtabs.html" %}
{% include "files/file_path.html" %}
{% include "report/report_panel.html" %}
{% endblock %}

{% block script %}
{{ super() }}
<script src="{{ url_for('static', filename='js/scaks/report.js') }}"></script>
{% endblock %}